// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Level    int64  `json:"level"`
	Sex      int64  `json:"sex"`
	IsAdmin  int64  `json:"is_admin"`
	Nickname string `json:"nickname"`
	Mobile   string `json:"mobile"`
	Email    string `json:"email"`
	Age      string `json:"age"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type RegisterReq struct {
	Nickname string `json:"nickname"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
	GoogleAuth   string `json:"googleAuth"`
}

type LoginReq struct {
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	GCode    string `json:"gcode"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}
